### ISSUE TITLE
username and password authentication

### ISSUE THREAD

**Issue by kskenyon** [InfiniteDevices/bacnet-mqtt-gateway#4]
Need help to use with mosquitto broker using username/password authentication.

Need to modify mqtt_client.js and default.json?

Kevin

**Comment by 2pk03** [comment]
Hey Kevin, yes the config needs to be adjusted:
https://github.com/InfiniteDevices/bacnet-mqtt-gateway/blob/master/config/default.json

**Comment by 2pk03** [comment]
solved

**Comment by kskenyon** [comment]
Not enough to edit default.json alone.  mqtt_client.js needs to modified to eliminate looking for cert paths and adding looking for username: and password:

refer to mqtt.js docs as needed.

**Comment by wendtc** [comment]
> mosquitto broker

hello I would also like to log in locally on a mosquitto broker with username and password. Can you please send me the necessary changes. Thank you Christian

**Comment by wendtc** [comment]
i didn't make it
