### ISSUE TITLE
not able to start gateway

### ISSUE THREAD

**Issue by thaker123** [InfiniteDevices/bacnet-mqtt-gateway#7]
i dont know why it's not working properly in my case.
when i start gateway it show error of mqtt.
 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for mqtt@>=5.6.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'app'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-17T19_53_34_296Z-debug.log

**Comment by BasemMohamed** [comment]
Yes, the same thing here. 

![Screenshot_2020-04-19_01-50-16](https://user-images.githubusercontent.com/17470573/79674084-2adceb00-81e0-11ea-86f7-bcca60a0e033.png)

**Comment by thaker123** [comment]
Still there is no any kind of solution comes from respected contributors, so please provide us  the appropriate solution.

**Comment by 2pk03** [comment]
Sorry, got out of view. Just fixed in the latest commit, the build comes now out clean. Also fixed some dep sec issues
