### ISSUE TITLE
mqtt dependency version

### ISSUE THREAD

**Issue by magicmatt007** [InfiniteDevices/bacnet-mqtt-gateway#8]
Hi,

I cloned the project to my Windows 10 machine.

"npm install" generates the error "No matching version found for mqtt@>=5.6.1." 

When checking on NPM for the latest version of mqtt, it says 4.2.6: (https://www.npmjs.com/package/mqtt)

Am I missing something?

Thx!

**Comment by 2pk03** [comment]
Hey @magicmatt007 ,

thanks for reporting, just fixed. Sorry that we took so long, we lost a bit the view :) I also fixed package.json, test builds are now clean.

best
