### ISSUE TITLE
Access to generic MQTT servers

### ISSUE THREAD

**Issue by magicmatt007** [InfiniteDevices/bacnet-mqtt-gateway#9]
Hi,

first of all thanks for fixing the mqtt dependency :-)

I just realized that this project seems to be focused on MQTT servers related to "INFINIMESH"*. Is this correct?

Anyhow, I'm wondering if I can use this gateway also for other MQTT servers like Mosquitto?

If so, I'd like to get started with using their (public) test server here: https://mqtt.eclipse.org/

The default.json seems to support only encrypted connections with Client side SSL authentication. (8884 : MQTT, encrypted, client certificate required). Is this correct? 

Any chance to use alternative connection methods like the ones being offered by the test server above:

- 1883 : MQTT over unencrypted TCP
- 8883 : MQTT over encrypted TCP

Many thanks!

* And if all of my wishes above cannot be fulfilled, how could I get access to a trial account of Infinimesh?

**Comment by 2pk03** [comment]
Hi, 

the gateway is open to any RFC compliant MQTT broker, as noted in the Readme:
"By default the gateway is configured to use infinimesh.cloud platform, but it can be used with any MQTT broker."

In fact we know from some dozen using this with Azure or AWS IoT. Just edit the config, that's all. An trial account for infimesh.cloud can be obtained by contact our sales directly (sales@infinitedevices.io) or click on the popup in console.infinimesh.cloud (contact also sales via a form).

We don't support alternative methods, we also encourage to only use MQTTS as protocol. But feel free to add alternatives, it's open source ;) Just to a PR and we check if the code works.

**Comment by 2pk03** [comment]
If you have more questions, we are happy to help :)
